
//couleurs des etoiles
#declare couleurO = rgb <0.61, 0.69, 1.0>;
#declare couleurB = rgb <0.67, 0.75, 1.0>;
#declare couleurA = rgb <0.79, 0.84, 1.0>;
#declare couleurF = rgb <0.97, 0.97, 1.0>;
#declare couleurG = rgb <1.0, 0.96, 0.92>;
#declare couleurK = rgb <1.0, 0.82, 0.63>;
#declare couleurM = rgb <1.0, 0.8, 0.43>;


//distance de la camera
#declare d_camera = <0, 10, -11.5>;

//echelle des irregularites de la surface
#declare echelle = 0.4;